### ISSUE TITLE
mimeytpes

### ISSUE THREAD

**Issue by gedw99** [odddollar/File-browser#1]
gee this works nicely.

I made a folder and uploaded a PDF, then viewed it. It did not work and loaded the pdf up in a text editor.

Maybe its better to have the view work in 2 stages ?
1. show the file based on the mimeytpe. so you can see the image or pdf.
2. then if they user wants they can show an editor for that file.

**Comment by odddollar** [comment]
It may be a possibility to have the ability to view images and pdfs in the future, but not in the immediate future.

**Comment by gedw99** [comment]
Ah I did not realise that was intended. 

No worries. Will close this then
