### ISSUE TITLE
htmx for faster client updates

### ISSUE THREAD

**Issue by gedw99** [odddollar/File-browser#2]
htmx allow patching the web gui and also sending data back 

https://htmx.org/examples/ shows the idea ....

golang support example.

https://github.com/Baralga/baralga-app/blob/main/shared/hx/htmx.go

**Comment by odddollar** [comment]
This looks really cool. Thanks for your suggestion!

However it would involve completely rewriting the front-end code, which is out of scope for this project at the moment. 

I'm actually quite happy with the relative simplicity of how File Browser works.
